// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1mFL6FyMz3QkZ4Ybw3AsnZnGeu0i9hFQ',
    appId: '1:814615635914:web:ba73a55b50c49030545133',
    messagingSenderId: '814615635914',
    projectId: 'coach-and-student',
    authDomain: 'coach-and-student.firebaseapp.com',
    storageBucket: 'coach-and-student.firebasestorage.app',
    measurementId: 'G-227ZKHGM7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNgc-4VF-dg1IXVwnc0edMeC865rTVzc',
    appId: '1:814615635914:android:baab2866dd6900a9545133',
    messagingSenderId: '814615635914',
    projectId: 'coach-and-student',
    storageBucket: 'coach-and-student.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6fvF-uTX_ESPy8pRQR6T6lzw4JgzhrnY',
    appId: '1:814615635914:ios:d15dbba6969719cc545133',
    messagingSenderId: '814615635914',
    projectId: 'coach-and-student',
    storageBucket: 'coach-and-student.firebasestorage.app',
    androidClientId: '814615635914-tv7a4mttbm0n1sk2hri4noqhdh2rh08s.apps.googleusercontent.com',
    iosClientId: '814615635914-ka420tsahv82olvh0m5gj1ql9cjrs9ut.apps.googleusercontent.com',
    iosBundleId: 'com.live.coachandstudent',
  );
}
